### ISSUE TITLE
Refactor Database to be a Service

### ISSUE THREAD

**Issue by jmankhan** [Muhlenberg-CUE-AR/Android#12]
It must extend AbstractService and be a singleton
see https://github.com/Muhlenberg-CUE-AR/Android/blob/master/app/src/main/java/muhlenberg/edu/cue/services/CUELocationService.java for reference.

Note that it should be appropriately abstracted such that the database will not be created or load any files until told to do so, and any references it has or operations it is performing should be disposable at will. This includes async operations.

**Comment by Mod-masta** [comment]
Not really sure what you mean. When are we telling it to load?

**Comment by jmankhan** [comment]
See https://github.com/Muhlenberg-CUE-AR/Android/blob/master/app/src/main/java/muhlenberg/edu/cue/MainActivity.java#L60

We should be able to call start() and stop() at any point in runtime. You shouldn't worry about loading it yourself, except for testing purposes. once we integrate the service, we can decide when and how to start it.

**Comment by Mod-masta** [comment]
Well to save data to the database you just need to call the POI() function from the Database file. So are you saying it should only load it when onResume is called? If so then I just need to call POI() there.
